language: go
before_install:
- echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ `lsb_release
  -cs` main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
- curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
- sudo apt-get install -y apt-transport-https
- sudo apt-get -qq update && sudo apt-get install -y azure-cli
go:
- '1.10.x'
script:
- ./build $TRAVIS_TAG
deploy:
  provider: script
  script: ./scripts/publish
  skip_cleanup: true
  on:
    tags: true
    branch: master
