#!/bin/bash

root=$(cd `dirname $0`; pwd)
version=$1
commit=${TRAVIS_COMMIT:-`git rev-parse --verify HEAD`}
echo "Version: ${version:=`date -u +local-%Y%m%d-%H%M%S`}"

export CGO_ENABLED=0

for os in linux; do  # add darwin and windows in the future
    export GOOS=$os
    mkdir -p $root/bin/$os

    for agent_name in `ls $root/agents`; do
        echo "Build $agent_name for $os"
        artifact=$root/bin/$os/a01$agent_name
        go build -o $artifact \
                 -ldflags "-X main.version=$version -X main.sourceCommit=$commit" \
                 agents/$agent_name/main.go
        chmod +x $artifact
    done
done