FROM alpine:3.7

RUN apk update && apk upgrade && \
    apk add --virtual=build && \
    apk add gcc make libffi-dev musl-dev openssl-dev python3 python3-dev && \
    ln /usr/bin/python3 /usr/bin/python && ln /usr/bin/pip3 /usr/bin/pip

COPY build /tmp/build

RUN find /tmp/build -name '*.whl' | xargs pip install && \
    find /tmp/build -name '*nspkg*.whl' | xargs pip install

COPY app /app
