#!/bin/bash

# This script builds and publishes a private build

set -e

version=$PRIVATE_BUILD_VER

if [ -z $version ]; then
    echo "You MUST define PRIVATE_BUILD_VER for build and release a private build"
    exit 1
fi

dp0=`cd $(dirname $0); pwd`
$dp0/../build "$PRIVATE_BUILD_VER+$USER+`date -u +%Y%m%d-%H%M%S`"

for os in linux ; do  # add darwin windows in the future
    sharename=${PRIVATE_BUILD_VER//./-}
    az storage share create -n $os-$sharename --quota 1 > /dev/null

    az storage file upload -s $os-$sharename --source ./bin/$os/a01droid --validate-content --no-progress
    az storage file upload -s $os-$sharename --source ./bin/$os/a01dispatcher --validate-content --no-progress

    az storage file list -s $os-$sharename -otable
done


